### ISSUE TITLE
Add support for Kubernetes

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#104]
## Overview

Add Kubernetes support for development environments as well as staging/production environments.

## Requirements (in no particular order)

- [x] Provide the necessary documentation and setup options to set up development environments that are compatible with Kubernetes
    - [ ] Dev setup with K3's and update contributor guide
- [x] Use the JupyterHub helm-chart as a sub chart [zero-to-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s)
- [x] Customize Helm chart based on IllumiDesk requirements
    - [x] Workspace base image references
    - [x] Custom authenticator(s)
    - [x] Custom spawner(s)
    - [x] PV/PVC for storage
    - [x] Environment variable references
    - [x] AWS specific manifests, such as aws-iam-authenticator and alb-ingress
    - [ ] Add option for internal NFS service for customers that don't want or have AWS EFS
    - [x] Add option for internal Postgres service for customers that don't want or have AWS RDS. The JupyterHub DB can continue to support SQLite as an option but the grader must use Postgres due to thread-safety.
- [x] Update setup-course service to create new grader services and folder structure when receiving requests for new courses
- [x] Add EFS/NFS PV/PVC and attach end-user workspaces to this storage option
- [x] Update IllumiDesk JupyterHub image to use the `illumidesk/jhub-k8:latest` image.
- [x] Refactor existing IllumiDesk base spawner class to inherit from the [KubeSpawner](https://github.com/jupyterhub/kubespawner)
- [x] Refactor jupyterhub base image to install IllumiDesk package with pip, either with a GitHub release or with pypi vs local copy/install using zip
- [x] Providing conditions for create custom configuration YMLs used by Helm to deploy and update stacks (epic, requires POCs to determine a) interface contracts between admin-dashboard and backend and b) implementation of how to create custom config so that Helm can use it.

**Comment by jgwerner** [comment]
@netoisc @Abhi94N fork [located here](https://github.com/IllumiDesk/zero-to-jupyterhub-k8s).

**Comment by jgwerner** [comment]
@Abhi94N @netoisc based on the latest requirements we discussed in Slack, I have updated the checklist to remove the CSS/JS requirements for the helm-chart so we can deal with that separately using a standard pip package(s) added to the docker images.

**Comment by jgwerner** [comment]
Closing! We are ignoring the options for K3s setup for dev, NFS (since the helm chart is now deprecated).
