### ISSUE TITLE
Add option to provide users with additional workspace types

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#147]
## Overview

In addition to allowing users to select their desired workspace type, allow users to specify the resources to run the container-based environments, such as CPU and memory options.

## Solution

- [ ] Allow administrators to select the workspace's spawner. For example, Jupyter Notebook with GPU using Kubernetes Spawner or THEIA IDE with Docker Swarm spawner.
- [ ] Allow users to specify multiple named workspaces, each with its own settings
- [ ] Allow users to launch workspaces using a standard form or pass query parameters to spawn container with the desired options
