### ISSUE TITLE
In-browser nbgrader POC (Starboard-based)

### ISSUE THREAD

**Issue by gzuidhof** [IllumiDesk/illumidesk#521]
## Summary
Create a [Starboard](https://github.com/gzuidhof/starboard-notebook)-based assignment creator and grading interface that is entirely clientside. Input for this module is a ipynb file (with nbgrader metadata), output is also an ipynb file with metadata.

## Background / Motivation

Gradually we aim to move the the grader workflow to a new infrastructure, including a new front-end that is more user intuitive. Large parts of IllumiDesk could run entirely in the browser, for instance the grading interface, and it makes a freemium offering more economically viable.

## Goals
* A webpage where you can drop in an ipynb file (with or without) nbgrader metadata.
* This notebook gets displayed in a Starboard notebook editor. 
* In this notebook there are special controls that allow you to do the same things as you can currently do in nbgrader (add manual feedback, add an assignment cell, ...).
* A button to download the resulting ipynb file.

## Non-goals
* Loading or uploading the ipynb file from any existing API. How we fit this module into the larger infrastructure is something we can decide and build later.

## Rough outline of work to be done
* [x] Create a repository where this lives (we can call it something like `starboard-nbgrader`). Do we want to open source this work?
* [x] Create a small demo page (where you can drop, interact with, and download the ipynb file).
* [x] Add support for keeping cell and notebook metadata in translation from jupyter->starboard in [Jupystar](https://github.com/gzuidhof/jupystar).
* [x] Add support in Jupystar for reverse translation (Starboard -> Jupyter ipynb).
* [x] Create a new cell type in Starboard that can be loaded dynamically (i.e. `nbgrader-python`), and the UI for this.
* [ ] Add a topbar in Starboard that displays some information related to nbgrader (e.g. "Total points" from nbgrader). This requires a bit of work in Starboard itself.

**Comment by jgwerner** [comment]
@gzuidhof this looks good to me! I'll create a new public repo for this POC and then we can start adding sub-issues in this new repo if needed. As a side note, I was wondering what your thoughts were on having a canonical version of the ipynb based on a format created by [Jupytext](https://github.com/mwouts/jupytext). It might make certain tasks a little less complicated, such as diffing versions of a Notebook before they are generated/released as assignments, but maybe I'm overcomplicating things?

**Comment by gzuidhof** [comment]
The in-browser grader PoC/MVP is pretty much done - all that remains is actual Python execution. That requires some refactoring to starboard-python itself (as it assumes you want to run Python only from within a Python cell, but now we want to run some Python from a grader cell), but aside from that the demo is there :).

Screenshots:
<img width="1635" alt="Screenshot 2021-03-16 at 18 13 35" src="https://user-images.githubusercontent.com/1039510/111362302-8597f480-8686-11eb-8f8b-f03771a46f11.png">
<img width="1166" alt="Screenshot 2021-03-16 at 18 33 51" src="https://user-images.githubusercontent.com/1039510/111362319-892b7b80-8686-11eb-80ab-4af6adc21e37.png">

PR with changes [here](https://github.com/IllumiDesk/starboard-nbgrader/pull/2).

---

The easiest way to demo this and integrate it further is through a NPM package, I propose we create one under the IllumiDesk organization (`@illumidesk/starboard-nbgrader` or something like that).
@jgwerner could you add me to the NPM org? My username is [gzuidhof](https://www.npmjs.com/~gzuidhof)

**Comment by jgwerner** [comment]
@gzuidhof this looks great! I agree that we just need to stick to Python and (perhaps?) JavaScript for now. Perhaps we could review the next steps sometime this week.

I'll go ahead and add you to the IllumiDesk NPM repo.
