### ISSUE TITLE
Grader/Assignment Creator POC Level 2

### ISSUE THREAD

**Issue by gzuidhof** [IllumiDesk/illumidesk#534]
This is the followup of [this epic issue](https://github.com/IllumiDesk/illumidesk/issues/521), this next step is mostly around improving the UI and UX by addressing some low hanging fruit.

The only thing we haven't completed from last epic is a top bar that shows info like "total points", I propose we defer that.

## Targets

* [x] Introduce a WYSIWYG(ish) editor such as Markdown for text blocks (ProseMirror seems like the best choice).
* [x] No longer display the grader cell ID (or at least hide it in some sort of "advanced" section in the future).
* [x] More obvious autograder test status (✅ vs ❌), hide stacktrace behind a "show details" button.
* [x] More friendly cell creation/type change interface (Gitbook style).
* [x] Publish starboard-nbgrader package to NPM

**Comment by gzuidhof** [comment]
Live demo: https://unpkg.com/@illumidesk/starboard-nbgrader@0.1.1/demo/index.html

**Comment by jgwerner** [comment]
@gzuidhof this looks great! I'll close this issue so we can focus on the other ones.
