### ISSUE TITLE
Create a Canvas LMS grades exporter

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#583]
**Problem**

Users need to export their grades in batch and cannot do so with the current LTI 1.3 compatible send grades feature. It's possible to update the LTI 1.3 compatible handlers to send grades in batch, however, exporting the grades as a CSV file supports additional use cases, such as supporting sending grades for users that still have LTI 1.1, have not integrated IllumiDesk with the LTI standard (i.e. standard OAuth2/RESTful services), etc.

**Solution**

Create a Canvas LMS CSV grades exporter for:

- All users for all assignments in a course
- All users for one assignment in a course
- A specific list of user(s) for a specific list of assignment(s) in a course

Tasks:

- [ ] Create an nbgrader export plugin to export assignment grades for the Canvas LMS
- [ ] Replicate export CSV tests from base [CsvExportPlugin](https://github.com/jupyter/nbgrader/blob/9309aaf2a75bbec81a2e78b01cee81b49b053001/nbgrader/plugins/export.py#L35) class
- [ ] Add custom handler with the `/export-canvas-grades` route to call CsvCanvasLmsGradesExportPlugin.export()
- [ ] Update nbgrader CLI or add new script (bash, python, etc) to include the option to export and download grades as a Canvas-compatible CSV file by calling custom handler

**Comment by jgwerner** [comment]
@rupeshparab the Canvas CSV import example is [located here](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-import-grades-in-the-Gradebook/ta-p/807). One of the required fields for the CSV is the Assignment ID. I have attached an example export using the guide from [Canvas Course grade book](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-export-grades-in-the-Gradebook/ta-p/809) from [this course](https://illumidesk.instructure.com/courses/295/gradebook).

Nbgrader is missing the assignment id. Some ideas:

- Have the user export grades and then sort students by username from the exported CSV and the one created from nbgrader so that they match. This option could work but is manual and error-prone.
- Fetch the assignment ID from Canvas before creating the CSV using the Canvas LMS Developer key with the client credentials with the client id and client secret. This second option is probably the most feasible and in this case we may not have to create the CSV but post the grades to Canvas directly.

For the second option above to work we would have to get the user's consent for us to register the client secret for the developer key.

**Comment by rupeshparab** [comment]
Hi @jgwerner 
I have finalized on the approach, I am planning to use a hybrid of the 2 approaches which you have suggested
This is how the user flow would look like:

1. User exports Canvas gradebook and copies in a Jupyter directory
2. Uses `nbgrader export` cli with our custom export plugin for Canvas and passes the location of the exported gradebook from Step 1.

as we have the exported notebook from Canvas, we can use the assignment ids to create the correct format file for Canvas import.
This method is manual, but is less error-prone

**Comment by jgwerner** [comment]
> Hi @jgwerner I have finalized on the approach, I am planning to use a hybrid of the 2 approaches which you have suggested This is how the user flow would look like:
> 
> 1. User exports Canvas gradebook and copies in a Jupyter directory
> 2. Uses `nbgrader export` cli with our custom export plugin for Canvas and passes the location of the exported gradebook from Step 1.
> 
> as we have the exported notebook from Canvas, we can use the assignment ids to create the correct format file for Canvas import. This method is manual, but is less error-prone

@rupeshparab sounds good. The only pending item then is to confirm how to register the plug-in, either by merging the work upstream with the nbgrader repo or creating our own CLI command to export grades. At first we could even add instructions so the user can create the file with `curl`.

**Comment by jgwerner** [comment]
Closed by #632
