### ISSUE TITLE
Migrate Grader to queue/task based system

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#584]
Migrate nbgrader's auto-grading service so that it runs asynchronously with a queue/task-based system.

- [x] New grading service should be compatible with the current [nbgrader schema](https://github.com/jupyter/nbgrader/blob/master/nbgrader/nbgraderformat/v3.json)
- [x] Implement a queue of (n) assignments to auto-grade (one, all, or something in between)
- [x] Implement a queue of (n) students to auto-grade (one, all, or something in between)
- [x] Maintain status for auto-grader jobs (Started, In-Progress, Succeeded, Failed)
- [ ] ~~Notifications to support alerts to end-users, backend administrators, etc. (SNS topics, etc).~~
- [x] Select the task/queue technology (Celery, SQS, Dask, Redit Queue, RabbitMQ, etc)

Examples:

- Grade all assignments for one student
- Grade all students for one assignment
- Grade all assignments for all students

**Comment by jgwerner** [comment]
Closed with the `illumidesk/async-nbgrader` package.
