### ISSUE TITLE
Create new backend Learning Management System (LMS) API

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#585]
Create a new backend for the "Light LMS".

- [x] Create Swagger 2.0 / Postman RESTful specification
- [x] Confirm ERD for Light LMS
- [x] Implement Authentication and Authorization with OAuth2/OIDC

Entities:

- [x] Assignments API
- [x] Courses API
- [x] Gradebook API
- [x] Groups API
- [x] Notebooks API
- [x] Submissions API
- [x] Users API (replaces Students API)

The current `nbgrader` database schema [is located here](https://lucid.app/lucidchart/bbbf52a4-d4a8-49b1-bf83-b563176bb5ae/edit?page=0_0#).

**Comment by jgwerner** [comment]
Closing now that we have code complete for all checklist items in `illumidesk/lms` repo.
