### ISSUE TITLE
Update User Experience (UX) for project endpoints

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#586]
This epic is to organize issues related to the new user interface Prototype used by Instructors, Teachers Assistants, Content Developers/Managers, and Students as a replacement for the standard Jupyter Classic and friends extension-based interface.

- [x] Provide the user with the option to create vanity domains from the current admin dashboard (https://app.illumidesk.com/login)
- [x] Update Org/Team invite users options so that they are routed to the correct project for access
- [x] Enable SSO between current Admin Dashboard and Projects (a.k.a. Stacks) so that users invited to a Project have the appropriate permissions for that Project only
- [x] Update third party IdMS with necessary attributes to enable RBAC (Instructor, Student, TA, etc)
- [x] Customize UX based on the user's role for the Project (access to Assignment Designer, access to distribution/collection/grading/feedback workflows, etc)

**Comment by jgwerner** [comment]
This is now code complete as documented in the `illumidesk/admin-dashboard` repo.
