### ISSUE TITLE
Enable anonymous to authenticated user flows for Starboard-based Notebooks and save files to remote storage

### ISSUE THREAD

**Issue by jgwerner** [IllumiDesk/illumidesk#590]
## Overview

This feature is geared toward allowing users to save their files using the Starboard-based Notebook to an S3 bucket. The first version of this file-save is to optimize the conversion rates for IllumiDesk's first campaign slated to launch on June 15th, 2021. However, this file-save feature is also the first move away from the shared NFS-based (currently with AWS EFS) files system to a file system based on S3 compatible object stores.

## Goals

The campaign mentioned above has the goal of testing conversions using the Marketing and Technology stack (Salesforce, ZoomInfo, Pardot, etc). By `conversion` we are referring to measuring an end-user sign-up for the [IllumiDesk application](https://app.illumidesk.com/login).

We will focus on the following goals to simplify the conversion efforts:

- [ ] Create a route that allows users to open a Notebook as an anonymous user.
- [ ] Add banner or CTA that prompts the anonymous user to save their work
- [ ] Provide the user a Registration option without losing their current state and location within the application
- [ ] Update the filesystem abstraction so the user can persist their files to an S3 bucket
- [ ] Determine logical grouping of the user's work (Project files, Account files, etc)

> This first campaign's goal is more focused on testing the full Marketing and Technology stack rather than measuring the outcome of actual conversions since this use-case does not emphasize IllumiDesk's value propositions (instructor and learner collaboration, grading, etc).
